//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIE
    {
        public int CIEId { get; set; }
        public string Category { get; set; }
        public string Test { get; set; }
        public string Assignment { get; set; }
        public string Quizzes { get; set; }
        public string CCA { get; set; }
        public Nullable<int> CourseId { get; set; }
    }
}
