//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public int CourseDetailId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CourseObjectiveId { get; set; }
        public Nullable<int> CLOId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> AssessmentStrategieId { get; set; }
        public Nullable<int> TeachingStrategieId { get; set; }
        public Nullable<int> CIEId { get; set; }
        public Nullable<int> SEEId { get; set; }
        public Nullable<int> BookId { get; set; }
    
        public virtual AssessmentStrategie AssessmentStrategie { get; set; }
        public virtual AssessmentStrategie AssessmentStrategie1 { get; set; }
        public virtual Book Book { get; set; }
        public virtual Book Book1 { get; set; }
        public virtual CIE CIE { get; set; }
        public virtual CIE CIE1 { get; set; }
        public virtual CLO CLO { get; set; }
        public virtual CLO CLO1 { get; set; }
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual CourseObjective CourseObjective { get; set; }
        public virtual CourseObjective CourseObjective1 { get; set; }
        public virtual LearningPlan LearningPlan { get; set; }
        public virtual LearningPlan LearningPlan1 { get; set; }
        public virtual SEE SEE { get; set; }
        public virtual SEE SEE1 { get; set; }
        public virtual TeachingStrategie TeachingStrategie { get; set; }
        public virtual TeachingStrategie TeachingStrategie1 { get; set; }
    }
}
