//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPAssessmentStrategie
    {
        public int LPAssessmentStrategieId { get; set; }
        public Nullable<int> AssessmentStrategieId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual AssessmentStrategie AssessmentStrategie { get; set; }
        public virtual AssessmentStrategie AssessmentStrategie1 { get; set; }
        public virtual LearningPlan LearningPlan { get; set; }
        public virtual LearningPlan LearningPlan1 { get; set; }
    }
}
