//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPCLO
    {
        public int LPCLOId { get; set; }
        public Nullable<int> CLOId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Outcomes { get; set; }
        public string CLOName { get; set; }
    
        public virtual CLO CLO { get; set; }
        public virtual Course Course { get; set; }
        public virtual LearningPlan LearningPlan { get; set; }
    }
}
